### ISSUE TITLE
Add Support for Multiple Stoves

### ISSUE THREAD

**Issue by garand** [garand/stove#3]
Create a new database table to store the stove information.

``` json
{
  "first_stove": {
    "latitude": "LATITUDE",
    "longitude": "LONGITUDE"
  },
  "second_stove": {
    "latitude": "LATITUDE",
    "longitude": "LONGITUDE"
  }
}
```

**Comment by garand** [comment]
After further contemplation, this would be better stored in a new database table.

**Comment by mattgraham** [comment]
I'd like to see some graphs on the two stoves and conditions. ;)

**Comment by garand** [comment]
You design them, I'll see what I can come up with.

**Comment by mattgraham** [comment]
So its an interesting issue because we need to know what metrics to use. Amount of wood 'used' vs. temperature outside? Amount of 'wood used' stove vs stove? Amount of 'wood used' vs time of year? Maybe yes to all but the only 'gauge' of amount of wood used is ```sum=(post fill - pre fill) ```

**Comment by mattgraham** [comment]
![image](https://cloud.githubusercontent.com/assets/51578/5598925/45312154-928c-11e4-89e7-ca926e0be6b8.png)

Left: Degrees
Bottom: Date
Bottom-Dots: Amount of times filled

**Comment by garand** [comment]
I like it. It doesn't include the wood level though.

**Comment by mattgraham** [comment]
what does wood level tell us? 


Matt Graham, UX Design & Strategy
kickthebox@gmail.com

**Comment by mattgraham** [comment]
obviously I know what it tells us, but what value does it give. 


Matt Graham, UX Design & Strategy
kickthebox@gmail.com

**Comment by garand** [comment]
¯\_(ツ)_/¯
